### ISSUE TITLE
Vagrant port forwarding should not use port 6000

### ISSUE THREAD

**Issue by alayek** [DevBlend/zenias#28] opened 2016-05-16 19:48 UTC
I tried running a Django app in port 6000, using `python manage.py runserver 0.0.0.0:6000`. My local browser could not connect to `localhost:6000`.

However, my terminal could. I could send a `curl -I http://localhost:6000` request from host machine to get response back from guest box.

Firefox told me browser is blocking the request because port 6000 is reserved for some other activity.

We need to select some other port for this. Maybe `3000`?

**Comment by byteknacker** [comment] 2016-05-16 19:51
This is not a bug really, it is due to the fact that some other virtual machine or something else is using the same port 6000 or even the same localhost port 8080. So the way to circumvent that right now is to manually get rid of all the rest of the VMs. You can do it most properly by using VirtualBox GUI and delete them manually. vagrant global-status will show everything but not quite sometimes, it is prune to errors. You cannot sometime vagrant destroy stuff due to many reasons. So please try to have a look at all your servers locally running and especially VirtualBox.

**Comment by byteknacker** [comment] 2016-05-16 19:52
We should add the feature in our next release to automate port forwarding address to be randomly changed so that it is not blocked at any time, it will figure out all ports being currently used and then assign each newly spawned virtual machine another random port and displays that to the user at the end in the terminal.

**Comment by alayek** [comment] 2016-05-16 19:55
Actually, I always run only one VM. I checked this with `netstat` command as well, and grepped for `':6000'`. Nothing was using port 6000, other than what I intended.

The point is, to an end-user, it would appear our box does not do port forwarding.

Here's a solution for better experience. We use a port on host box randomly, a big number that is unlikely to be used by other running VM's, if any. Maybe something like 12,341.

And we export this `$PORT` environment variable during provisioining, so user doesn't need to know which random port is being assigned to the server. As for host box, let's use something a bit uncommon too, like 7778.

**Comment by byteknacker** [comment] 2016-05-16 19:59
@alayek when you say client and host machines, I somehow always confuse them, which one is which? Is the client machine the local laptop of the user such as the MacBook Pro? 

Yes, if there is absolutely no problem of assigning for the VM such a big port number, why not. 7778 is good since it is not standard for anything. But the key is to later automate this assignment. 

Also there is a way to assign to the vagrant VM a specific name so you can reference it much quicker from the vagrant global-status command or it will be displayed nicely under a good nickname inside virtualbox GUI, but this is not necessary and can destroy the multi-vagrant-box development modus.

**Comment by alayek** [comment] 2016-05-26 17:35
I think we already modified it to some extent, by using port 5000. It technically solves the issue, but I want to patch it in a way, that it makes a more intelligent decision in Vagrantfile and assigns a safe port somewhat carefully.

**Comment by byteknacker** [comment] 2016-05-28 18:22
@alayek do you still have this problem? I noticed that to have the port forwarding to work properly, you need to match what is written in your Vagrantfile and what is printed in the terminal while doing vagrant up or zeus.py newproject the forwarding port. Say if vagrant forwards 5000 to 5000, then you cannot run python manage.py runserver 6000 since this is not forwarded. You can do it for 5000 and in your local browser it will work.

**Comment by alayek** [comment] 2016-05-28 19:05
Yes, the port forwarding is working fine for me. But I was hoping we would add some nifty robust feature so that it works on most machines.

It's doable, `Vagrantfile` is mostly Ruby, so it would be a while-loop with an if-else test I guess.

**Comment by byteknacker** [comment] 2016-05-28 19:11
Yes I think so, I cannot do Ruby yet. Maybe we should let a ruby programmer do it.

**Comment by dragon788** [comment] 2016-05-29 15:42
You can add auto_correct: true to your port forward in order to have it detect collisions and increase the port number by 1 to avoid conflicts.

**Comment by dragon788** [comment] 2016-05-29 15:43
My suggestion would be if there are specific ports that a stack requires you could read an options file that lists which stack a user chose and forward those ports for them.

**Comment by byteknacker** [comment] 2016-05-29 15:44
Great point, I will do that for ports using this method, didn't think of that

**Closed as completed** 2016-06-18 10:02 UTC
Labels: bug, question
